### PR TITLE
Refactor npm2rpm

### LINKED ISSUE #40: Download packages with "/" in its name
Hi.

I'm trying to convert https://www.npmjs.com/package/@sellside/emitter to rpm, but am unable to.

Do you have any ideas on how I can achieve this?

TIA.

### PR DESCRIPTION
**Pull request by ekohl**
This is a pretty big rewrite to address various issues around package naming. NPM allows packages to be named as @group/package which creates issues when mapping to RPMs since we want to avoid slashes. They create directories on the filesystem and appears to break some assumptions.

To address this we normalize package names (see getRpmPackageName). We also stop downloading dependencies altogether. The user is now required to do this themselves. The suggested solution is:

spectool -g nodejs-*.spec.

We also made the output directory configurable. To do this we did flatten the structure. This makes it easier to integrate into the packaging structure we use in foreman-packaging.

The big downside is that if two dependencies have the same name but in a different namespace, we can't support this because the resulting filename is the same. This is currently a known limitation.

It also moves from var to const and string interpolation to create a more modern javascript style.

Other fixes included are around NPM dependencies in the package itself.

Fixes GH-40

### CODE REVIEW

**Review by dLobatog — APPROVED** [review]
This looks great overall, you definitely put some work into it @ekohl :+1: !

I wonder what's the reason why downloading the dependencies automatically isn't desirable anymore? I saw this works fine with https://github.com/theforeman/foreman-packaging/pull/3051 , so in general :+1:

**Comment by ekohl** [comment]
@dLobatog I can't see the snyk output. Can you see which vulnerable dependency it's not happy with?

**Comment by ehelms** [comment]
ping @dLobatog any chance you could get to the request? Would be appreciated!

**Comment by ekohl** [comment]
@dLobatog merging this now since it started to break with modern dependencies/nodejs and this fixes the callback.

**Pull request merged**
